/*
SQLyog Enterprise - MySQL GUI v6.5
MySQL - 5.1.37-community : Database - turistainteligente
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

create database if not exists `turistainteligente`;

USE `turistainteligente`;

/*Table structure for table `cliente` */

DROP TABLE IF EXISTS `cliente`;

CREATE TABLE `cliente` (
  `ID_CLIENTE` int(11) NOT NULL AUTO_INCREMENT,
  `NOMBRE` varchar(50) NOT NULL,
  `PRIMER_APELLIDO` varchar(50) NOT NULL,
  `SEGUNDO_APELLIDO` varchar(50) DEFAULT NULL,
  `EMAIL` varchar(100) NOT NULL,
  `TELEFONO` varchar(25) NOT NULL,
  `SEGUNDO_TELEFONO` varchar(25) DEFAULT NULL,
  `CEDULA` varchar(25) DEFAULT NULL,
  `EMPRESA` varchar(100) DEFAULT NULL,
  `USR_REGISTRO` varchar(50) NOT NULL,
  `FEC_REGISTRO` datetime NOT NULL,
  `USR_MODIFICACION` varchar(50) DEFAULT NULL,
  `FEC_MODIFICACION` datetime DEFAULT NULL,
  PRIMARY KEY (`ID_CLIENTE`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;

/*Data for the table `cliente` */

insert  into `cliente`(`ID_CLIENTE`,`NOMBRE`,`PRIMER_APELLIDO`,`SEGUNDO_APELLIDO`,`EMAIL`,`TELEFONO`,`SEGUNDO_TELEFONO`,`CEDULA`,`EMPRESA`,`USR_REGISTRO`,`FEC_REGISTRO`,`USR_MODIFICACION`,`FEC_MODIFICACION`) values (1,'22','22','22','22','22','22','22','22','admin','2013-06-04 13:28:00',NULL,NULL);

/*Table structure for table `paquete` */

DROP TABLE IF EXISTS `paquete`;

CREATE TABLE `paquete` (
  `ID_PAQUETE` int(11) NOT NULL AUTO_INCREMENT,
  `ID_TIPO_PAQUETE_NAC` int(11) DEFAULT NULL,
  `ID_TIPO_PAQUETE_INT` int(11) DEFAULT NULL,
  `NOMBRE_PAQUETE` varchar(50) NOT NULL,
  `DESCRIPCION_SERVICIOS` varchar(1000) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
  `FECHA_INICIO` datetime DEFAULT NULL,
  `FECHA_FINAL` datetime DEFAULT NULL,
  `USR_REGISTRO` varchar(50) NOT NULL,
  `FEC_REGISTRO` datetime NOT NULL,
  `USR_MODIFICACION` varchar(50) DEFAULT NULL,
  `FEC_MODIFICACION` datetime DEFAULT NULL,
  PRIMARY KEY (`ID_PAQUETE`),
  KEY `FK_REFERENCE_TIPOPAQUETEINT_PAQUETE` (`ID_TIPO_PAQUETE_INT`),
  KEY `FK_REFERENCE_TIPOPAQUETENAC_PAQUETE` (`ID_TIPO_PAQUETE_NAC`),
  CONSTRAINT `FK_REFERENCE_TIPOPAQUETENAC_PAQUETE` FOREIGN KEY (`ID_TIPO_PAQUETE_NAC`) REFERENCES `tipo_paquete_nac` (`ID_TIPO_PAQUETE_NAC`),
  CONSTRAINT `FK_REFERENCE_TIPOPAQUETEINT_PAQUETE` FOREIGN KEY (`ID_TIPO_PAQUETE_INT`) REFERENCES `tipo_paquete_int` (`ID_TIPO_PAQUETE_INT`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;

/*Data for the table `paquete` */

insert  into `paquete`(`ID_PAQUETE`,`ID_TIPO_PAQUETE_NAC`,`ID_TIPO_PAQUETE_INT`,`NOMBRE_PAQUETE`,`DESCRIPCION_SERVICIOS`,`FECHA_INICIO`,`FECHA_FINAL`,`USR_REGISTRO`,`FEC_REGISTRO`,`USR_MODIFICACION`,`FEC_MODIFICACION`) values (1,1,NULL,'22','22',NULL,NULL,'admin','2013-06-04 13:55:46',NULL,NULL);

/*Table structure for table `proveedor` */

DROP TABLE IF EXISTS `proveedor`;

CREATE TABLE `proveedor` (
  `ID_PROVEEDOR` int(11) NOT NULL AUTO_INCREMENT,
  `NOMBRE` varchar(100) NOT NULL,
  `TELEFONO` varchar(25) NOT NULL,
  `SEGUNDO_TELEFONO` varchar(25) DEFAULT NULL,
  `PRIMERA_CUENTA` varchar(50) NOT NULL,
  `BANCO_PRIM_CUENTA` varchar(50) NOT NULL,
  `SEGUNDA_CUENTA` varchar(50) DEFAULT NULL,
  `BANCO_SDA_CUENTA` varchar(50) DEFAULT NULL,
  `IND_SINPE_PRIM_CUENTA` char(1) NOT NULL,
  `IND_SINPE_SDA_CUENTA` char(1) DEFAULT NULL,
  `IND_MONEDA_PRIM_CUENTA` char(1) NOT NULL,
  `IND_MONEDA_SDA_CUENTA` char(1) DEFAULT NULL,
  `IND_IMP_SWIFT` char(1) DEFAULT NULL,
  `IND_IMP_AVA` char(1) DEFAULT NULL,
  `IND_COMISION` char(1) DEFAULT NULL,
  `IND_CREDITO` char(1) DEFAULT NULL,
  `CANT_DIAS_CREDITO` int(11) DEFAULT NULL,
  `USR_REGISTRO` varchar(50) NOT NULL,
  `FEC_REGISTRO` datetime NOT NULL,
  `USR_MODIFICACION` varchar(50) DEFAULT NULL,
  `FEC_MODIFICACION` datetime DEFAULT NULL,
  PRIMARY KEY (`ID_PROVEEDOR`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Data for the table `proveedor` */

/*Table structure for table `proveedores_reservacion` */

DROP TABLE IF EXISTS `proveedores_reservacion`;

CREATE TABLE `proveedores_reservacion` (
  `ID_RESERVACION` int(11) NOT NULL,
  `ID_PROVEEDOR` int(11) NOT NULL,
  PRIMARY KEY (`ID_RESERVACION`,`ID_PROVEEDOR`),
  KEY `FK_REFERENCE_PROVEEDOR_PROVRES` (`ID_PROVEEDOR`),
  CONSTRAINT `FK_REFERENCE_RESERVACION_PROVRES` FOREIGN KEY (`ID_RESERVACION`) REFERENCES `reservacion` (`ID_RESERVACION`),
  CONSTRAINT `FK_REFERENCE_PROVEEDOR_PROVRES` FOREIGN KEY (`ID_PROVEEDOR`) REFERENCES `proveedor` (`ID_PROVEEDOR`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Data for the table `proveedores_reservacion` */

/*Table structure for table `reservacion` */

DROP TABLE IF EXISTS `reservacion`;

CREATE TABLE `reservacion` (
  `ID_RESERVACION` int(11) NOT NULL AUTO_INCREMENT,
  `ID_PAQUETE` int(11) DEFAULT NULL,
  `ID_TARIFA_RESERVACION` int(11) DEFAULT NULL,
  `ID_CLIENTE` int(11) DEFAULT NULL,
  `IND_ESTADO` char(1) NOT NULL,
  `NUM_CONFIRMACION` decimal(6,0) NOT NULL,
  `FECHA_PAGO_INICIO` datetime DEFAULT NULL,
  `FECHA_PAGO_FINAL` datetime DEFAULT NULL,
  `FECHA_LLEGADA` datetime DEFAULT NULL,
  `FECHA_SALIDA` datetime DEFAULT NULL,
  `USR_REGISTRO` varchar(50) NOT NULL,
  `FEC_REGISTRO` datetime NOT NULL,
  `USR_MODIFICACION` varchar(50) DEFAULT NULL,
  `FEC_MODIFICACION` datetime DEFAULT NULL,
  PRIMARY KEY (`ID_RESERVACION`),
  KEY `FK_REFERENCE_CLIENTE_RESERVACION` (`ID_CLIENTE`),
  KEY `FK_REFERENCE_PAQUETE_RESERVACION` (`ID_PAQUETE`),
  KEY `FK_REFERENCE_TARIFARESERVACION_RESERVACION` (`ID_TARIFA_RESERVACION`),
  CONSTRAINT `FK_REFERENCE_CLIENTE_RESERVACION` FOREIGN KEY (`ID_CLIENTE`) REFERENCES `cliente` (`ID_CLIENTE`),
  CONSTRAINT `FK_REFERENCE_PAQUETE_RESERVACION` FOREIGN KEY (`ID_PAQUETE`) REFERENCES `paquete` (`ID_PAQUETE`),
  CONSTRAINT `FK_REFERENCE_TARIFARESERVACION_RESERVACION` FOREIGN KEY (`ID_TARIFA_RESERVACION`) REFERENCES `tarifa_reservacion` (`ID_TARIFA_RESERVACION`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Data for the table `reservacion` */

/*Table structure for table `tarifa_habitacion` */

DROP TABLE IF EXISTS `tarifa_habitacion`;

CREATE TABLE `tarifa_habitacion` (
  `ID_TARIFA_HABITACION` int(11) NOT NULL AUTO_INCREMENT,
  `TIPO_HABITACION` varchar(20) NOT NULL,
  `CANTIDAD` decimal(2,0) NOT NULL,
  `USR_REGISTRO` varchar(50) NOT NULL,
  `FEC_REGISTRO` datetime NOT NULL,
  `USR_MODIFICACION` varchar(50) DEFAULT NULL,
  `FEC_MODIFICACION` datetime DEFAULT NULL,
  `MONTO_PERSONA` decimal(8,0) NOT NULL,
  `MONTO_NINIO` decimal(8,0) DEFAULT NULL,
  PRIMARY KEY (`ID_TARIFA_HABITACION`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;

/*Data for the table `tarifa_habitacion` */

insert  into `tarifa_habitacion`(`ID_TARIFA_HABITACION`,`TIPO_HABITACION`,`CANTIDAD`,`USR_REGISTRO`,`FEC_REGISTRO`,`USR_MODIFICACION`,`FEC_MODIFICACION`,`MONTO_PERSONA`,`MONTO_NINIO`) values (2,'22','22','admin','2013-06-04 13:55:46',NULL,NULL,'22','22');

/*Table structure for table `tarifa_paquete` */

DROP TABLE IF EXISTS `tarifa_paquete`;

CREATE TABLE `tarifa_paquete` (
  `ID_TARIFA_PAQUETE` int(11) NOT NULL AUTO_INCREMENT,
  `CANT_ADULTO_NAC` int(11) DEFAULT NULL,
  `CANT_ADULTO_INT` int(11) DEFAULT NULL,
  `CANT_NINIO_NAC` int(11) DEFAULT NULL,
  `CANT_NINIO_INT` int(11) DEFAULT NULL,
  `MONTO_ADULTO_NAC` decimal(10,2) DEFAULT NULL,
  `MONTO_ADULTO_INT` decimal(10,2) DEFAULT NULL,
  `MONTO_NINIO_NAC` decimal(10,2) DEFAULT NULL,
  `MONTO_NINIO_INT` decimal(10,2) DEFAULT NULL,
  `USR_REGISTRO` varchar(50) NOT NULL,
  `FEC_REGISTRO` datetime NOT NULL,
  `USR_MODIFICACION` varchar(50) DEFAULT NULL,
  `FEC_MODIFICACION` datetime DEFAULT NULL,
  PRIMARY KEY (`ID_TARIFA_PAQUETE`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;

/*Data for the table `tarifa_paquete` */

insert  into `tarifa_paquete`(`ID_TARIFA_PAQUETE`,`CANT_ADULTO_NAC`,`CANT_ADULTO_INT`,`CANT_NINIO_NAC`,`CANT_NINIO_INT`,`MONTO_ADULTO_NAC`,`MONTO_ADULTO_INT`,`MONTO_NINIO_NAC`,`MONTO_NINIO_INT`,`USR_REGISTRO`,`FEC_REGISTRO`,`USR_MODIFICACION`,`FEC_MODIFICACION`) values (1,33,33,33,33,'33.00','33.00','33.00','33.00','admin','2013-06-04 13:56:39',NULL,NULL);

/*Table structure for table `tarifa_reservacion` */

DROP TABLE IF EXISTS `tarifa_reservacion`;

CREATE TABLE `tarifa_reservacion` (
  `ID_TARIFA_RESERVACION` int(11) NOT NULL AUTO_INCREMENT,
  `CANT_ADULTO_NAC` int(11) DEFAULT NULL,
  `CANT_ADULTO_INT` int(11) DEFAULT NULL,
  `CANT_NINIO_NAC` int(11) DEFAULT NULL,
  `CANT_NINIO_INT` int(11) DEFAULT NULL,
  `MONTO_ADULTO_NAC` decimal(10,2) DEFAULT NULL,
  `MONTO_ADULTO_INT` decimal(10,2) DEFAULT NULL,
  `MONTO_NINIO_NAC` decimal(10,2) DEFAULT NULL,
  `MONTO_NINIO_INT` decimal(10,2) DEFAULT NULL,
  `USR_REGISTRO` varchar(50) NOT NULL,
  `FEC_REGISTRO` datetime NOT NULL,
  `USR_MODIFICACION` varchar(50) DEFAULT NULL,
  `FEC_MODIFICACION` datetime DEFAULT NULL,
  `TIPO_HABITACION` varchar(20) DEFAULT NULL,
  `CANTIDAD` decimal(2,0) DEFAULT NULL,
  `MONTO_PERSONA` decimal(8,2) DEFAULT NULL,
  `MONTO_NINIO` decimal(8,2) DEFAULT NULL,
  PRIMARY KEY (`ID_TARIFA_RESERVACION`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Data for the table `tarifa_reservacion` */

/*Table structure for table `tipo_paquete_int` */

DROP TABLE IF EXISTS `tipo_paquete_int`;

CREATE TABLE `tipo_paquete_int` (
  `ID_TIPO_PAQUETE_INT` int(11) NOT NULL AUTO_INCREMENT,
  `ID_TARIFA_PAQUETE` int(11) DEFAULT NULL,
  `ID_TARIFA_HABITACION` int(11) DEFAULT NULL,
  `LOCALIDAD` varchar(25) NOT NULL,
  `TIPO_VEHICULO` varchar(25) DEFAULT NULL,
  `TIPO_TRASLADO` varchar(25) DEFAULT NULL,
  `TIPO_TARIFA` varchar(25) NOT NULL,
  `LUGAR_SALIDA` varchar(100) DEFAULT NULL,
  `LUGAR_LLEGADA` varchar(100) DEFAULT NULL,
  `DIRECCION` varchar(500) DEFAULT NULL,
  `HOTEL` varchar(100) DEFAULT NULL,
  `OBSERVACIONES` varchar(1000) DEFAULT NULL,
  `USR_REGISTRO` varchar(50) NOT NULL,
  `FEC_REGISTRO` datetime NOT NULL,
  `USR_MODIFICACION` varchar(50) DEFAULT NULL,
  `FEC_MODIFICACION` datetime DEFAULT NULL,
  PRIMARY KEY (`ID_TIPO_PAQUETE_INT`),
  KEY `FK_REFERENCE_TARIFAHAB_TIPOPAQINT` (`ID_TARIFA_HABITACION`),
  KEY `FK_REFERENCE_TARIFAPAQ_TIPOPAQINT` (`ID_TARIFA_PAQUETE`),
  CONSTRAINT `FK_REFERENCE_TARIFAHAB_TIPOPAQINT` FOREIGN KEY (`ID_TARIFA_HABITACION`) REFERENCES `tarifa_habitacion` (`ID_TARIFA_HABITACION`),
  CONSTRAINT `FK_REFERENCE_TARIFAPAQ_TIPOPAQINT` FOREIGN KEY (`ID_TARIFA_PAQUETE`) REFERENCES `tarifa_paquete` (`ID_TARIFA_PAQUETE`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;

/*Data for the table `tipo_paquete_int` */

insert  into `tipo_paquete_int`(`ID_TIPO_PAQUETE_INT`,`ID_TARIFA_PAQUETE`,`ID_TARIFA_HABITACION`,`LOCALIDAD`,`TIPO_VEHICULO`,`TIPO_TRASLADO`,`TIPO_TARIFA`,`LUGAR_SALIDA`,`LUGAR_LLEGADA`,`DIRECCION`,`HOTEL`,`OBSERVACIONES`,`USR_REGISTRO`,`FEC_REGISTRO`,`USR_MODIFICACION`,`FEC_MODIFICACION`) values (1,1,NULL,'Centroamérica','Colectivo','Compartido','Personas','33','33','33','33','33','admin','2013-06-04 13:56:39',NULL,NULL);

/*Table structure for table `tipo_paquete_nac` */

DROP TABLE IF EXISTS `tipo_paquete_nac`;

CREATE TABLE `tipo_paquete_nac` (
  `ID_TIPO_PAQUETE_NAC` int(11) NOT NULL AUTO_INCREMENT,
  `ID_TARIFA_PAQUETE` int(11) DEFAULT NULL,
  `ID_TARIFA_HABITACION` int(11) DEFAULT NULL,
  `TIPO_TARIFA` varchar(25) NOT NULL,
  `DESCRIPCION_SERVICIOS` varchar(1000) DEFAULT NULL,
  `HOTEL` varchar(100) DEFAULT NULL,
  `OBSERVACIONES` varchar(1000) DEFAULT NULL,
  `USR_REGISTRO` varchar(50) NOT NULL,
  `FEC_REGISTRO` datetime NOT NULL,
  `USR_MODIFICACION` varchar(50) DEFAULT NULL,
  `FEC_MODIFICACION` datetime DEFAULT NULL,
  PRIMARY KEY (`ID_TIPO_PAQUETE_NAC`),
  KEY `FK_REFERENCE_TARIFAHAB_TIPOPAQNAC` (`ID_TARIFA_HABITACION`),
  KEY `FK_REFERENCE_TARIFAPAQ_TIPOPAQ` (`ID_TARIFA_PAQUETE`),
  CONSTRAINT `FK_REFERENCE_TARIFAHAB_TIPOPAQNAC` FOREIGN KEY (`ID_TARIFA_HABITACION`) REFERENCES `tarifa_habitacion` (`ID_TARIFA_HABITACION`),
  CONSTRAINT `FK_REFERENCE_TARIFAPAQ_TIPOPAQ` FOREIGN KEY (`ID_TARIFA_PAQUETE`) REFERENCES `tarifa_paquete` (`ID_TARIFA_PAQUETE`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;

/*Data for the table `tipo_paquete_nac` */

insert  into `tipo_paquete_nac`(`ID_TIPO_PAQUETE_NAC`,`ID_TARIFA_PAQUETE`,`ID_TARIFA_HABITACION`,`TIPO_TARIFA`,`DESCRIPCION_SERVICIOS`,`HOTEL`,`OBSERVACIONES`,`USR_REGISTRO`,`FEC_REGISTRO`,`USR_MODIFICACION`,`FEC_MODIFICACION`) values (1,NULL,2,'Habitaciones',NULL,'22','22','admin','2013-06-04 13:55:46',NULL,NULL);

/*Table structure for table `usuario` */

DROP TABLE IF EXISTS `usuario`;

CREATE TABLE `usuario` (
  `ID_USUARIO` int(11) NOT NULL AUTO_INCREMENT,
  `NOMBRE` varchar(50) NOT NULL,
  `PRIMER_APELLIDO` varchar(50) NOT NULL,
  `SEGUNDO_APELLIDO` varchar(50) DEFAULT NULL,
  `EMAIL` varchar(100) NOT NULL,
  `PASSWORD` varchar(25) NOT NULL,
  `IND_TIPO` char(1) NOT NULL,
  `TELEFONO` varchar(25) DEFAULT NULL,
  `USR_REGISTRO` varchar(50) NOT NULL,
  `FEC_REGISTRO` datetime NOT NULL,
  `USR_MODIFICACION` varchar(50) DEFAULT NULL,
  `FEC_MODIFICACION` datetime DEFAULT NULL,
  PRIMARY KEY (`ID_USUARIO`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;

/*Data for the table `usuario` */

insert  into `usuario`(`ID_USUARIO`,`NOMBRE`,`PRIMER_APELLIDO`,`SEGUNDO_APELLIDO`,`EMAIL`,`PASSWORD`,`IND_TIPO`,`TELEFONO`,`USR_REGISTRO`,`FEC_REGISTRO`,`USR_MODIFICACION`,`FEC_MODIFICACION`) values (1,'admin','admin','admin','admin','123456','A','admin','admin','2013-05-05 00:00:00',NULL,NULL);

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
